PRC-161 : Manage contact emergency flag
ministryofjustice/hmpps-contacts-ui pull request #137
Opened 2024-11-15 16:27 UTC by prabash-moj

PRC-161 : Manage contact emergency flag

2024-11-15 16:33 UTC, prabash-moj commented on server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
> +
I am hoping I can update this for other scenrios and reuse,

2024-11-15 16:44 UTC, james-baker-moj requested changes
Need to make work with the returnUrl stuff properly as per slack thread

2024-11-15 18:06 UTC, prabash-moj commented on server/views/pages/contacts/manage/contactDetails/manageRelationshipDetails.njk
> +                         href: prisonerContactId +"/emergency-contact",
Hmm this is working with  `href: prisonerContactId +"/emergency-contact",` I noticed the prisonerContactId and added that already, 
Updated with return url, 

Was thinking something was missing :) , wanted to come back to the return url thing and completely missed that,.

2024-11-15 18:12 UTC, prabash-moj commented on integration_tests/e2e/manageEmergencyContact.cy.ts
> +  })
added that, 

I prefer more unit tests/cheerio tests than cypress tests . so skiped those back and cancel flows as I have added good cheerios tests for those. 

But also I know for back and cancel is quick and easy one , 👍

2024-11-15 18:15 UTC, prabash-moj commented on server/routes/contacts/manage/manageContactsRoutes.ts
> +    populatePrisonerDetailsIfInCaseload(prisonerSearchService, auditService),
added to all the relevant places suggested in other comments as well

2024-11-15 18:17 UTC, prabash-moj commented on server/data/contactsApiClient.ts
> +    return this.patch<UpdateRelationshipRequest>(
didn't notice Intellij added that :(

2024-11-15 18:25 UTC, prabash-moj commented on server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
> +
I will update this for relationship, next of kin , comments , active scenarios, just need to pass the right json object only, 

This test does not do much - only it is testing true or false values showing YES or NO correctly, Mostly repetitive code,

2024-11-18 08:39 UTC, james-baker-moj commented on integration_tests/e2e/manageEmergencyContact.cy.ts
> +  })
yes but as we are injecting the returnUrl now the unit tests only check that it goes to what is specified. This makes sure it works in the real world

2024-11-18 08:40 UTC, james-baker-moj approved these changes
LGTM

2024-11-18 08:54 UTC, merged